import Head from "next/head";
import Image from "next/image";
import localFont from "next/font/local";
import styles from "@/styles/Home.module.css";
import Link from "next/link";
import Headers from "@/components/header/Header";
import Footers from "@/components/footer/Footer";
import Herocomp from "@/components/hero/Herocomp";
import Banner from "@/components/banner/Banner";
import { useEffect, useState } from "react";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export default function Home() {

  const [data,setData] = useState([])

    useEffect(() => {
        const fetchData = async () => {
          const res = await fetch("https://fakestoreapi.com/products");
          const result = await res.json();
          setData(result);
        };
        fetchData();
      }, []);

      console.log("getServerSidePropsgetServerSideProps",data);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <div className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`} > */}
      <div  >
        <main className={styles.main}>
          <Headers/>
          <Banner title="Welcome to My Site" subtitle="This is a sample banner created in Next.js"/>
          <Herocomp cardData = {data}/>          
          <Footers/>
        </main>        
      </div>
    </>
  );
}
